---
title: "Are the vegetation classes distinguishable according to the fire frequency model?"
author: "Jean Marchal"
date: "March, 7th 2019"
output: html_document
---

```{r setup}
library(dplyr)
library(magrittr)
library(MASS)
library(reproducible)
library(SpaDES)

ff_var <- "n_fires"

setPaths(
  inputPath = "../inputs",
  outputPath = "../outputs",
  modulePath = ".."
)

mk_formula <- function(to_merge, pw = TRUE)
{
  as.formula(
    paste0(
      ff_var,
      "~",
      do.call(
        "paste",
        c(
          lapply(
            to_merge,
            function(x)
            {
              x <- paste0("cl", x)
              
              f_str <- paste0("I(", paste(x, collapse = "+"), "):MDC06")
              
              if (pw) f_str <- paste0(
                f_str, "+ I(", 
                paste(x, collapse = "+"), 
                "):pw(MDC06, k_",
                paste(x, collapse = "_"),
                ")"
              )
              f_str
            }
          ),
          list(sep = "+")
        )
      ),
      "- 1"
    )
  )
}

fit <- function(formula, data, itermax = 500)
{
  set.seed(1)
  
  modules <- list("fireSense_FrequencyFit")
  
  objects <- list(dataFireSense_FrequencyFit = data)
  
  parameters <- list(
    fireSense_FrequencyFit = list(
      formula = formula,
      family = negative.binomial(1, link = "identity"),
      data = "dataFireSense_FrequencyFit",
      ub = list(coef = 1),
      nCores = 1,
      itermax = 5,
      nTrials = 1,
      trace = 5
    )	
  )
  
  times <- list(start = 1, end = 1)
  
  sim <- simInit(
    objects = objects,
    params = parameters,
    modules = modules,
    times = times
  )
  
  spades(sim)
}
```

```{R}
#
# Filter out pixels where at least one variable evaluates to 0
#
## Start by loading the data
#
dataFireSense_FrequencyFit <- readRDS(
  file.path(
    getPaths()$inputPath, 
    "dataFireSense_FrequencyFit.rds"
  )
)

#
## Filter out pixels where none of the classes of interest are present
#
dataFireSense_FrequencyFit %<>%
  dplyr::filter(
    (
      dplyr::select(., paste0("cl", c(1:32, 34:35))) %>% # 33, 36:39 do not burn. No need to estimate coefficients, it's 0.
        rowSums()
    ) != 0
  )

#
## Filter out pixels where MDC06 is > 0
#
dataFireSense_FrequencyFit %<>% dplyr::filter(MDC06 > 0)
```

Start with 5 classes: Conifer, Disturbed, Non-treed, Other treed (Deciduous + Mixed), Wetlands

  * Non-Piecewise
  
```{R}
fitted_5cl <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10, 20),  # Conifer
      c(34:35),        # Disturbed
      c(16:19, 21:32), # Non-treed
      c(2:5, 11:15),   # Other treed
      19               # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r fitted_5cl$fireSense_FrequencyFitted$convergence`\
AIC: `r fitted_5cl$fireSense_FrequencyFitted$AIC`

  * Piecewise
  
```{R}
fitted_5cl_pw <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10, 20),  # Conifer
      c(34:35),        # Disturbed
      c(16:19, 21:32), # Non-treed
      c(2:5, 11:15),   # Other treed
      19               # Wetlands
    )
  ), 
  dataFireSense_FrequencyFit,
  itermax = 2000
)
```

Convergence: `r fitted_5cl_pw$fireSense_FrequencyFitted$convergence`\
AIC: `r fitted_5cl_pw$fireSense_FrequencyFitted$AIC`

Piecewise model did not converge, proceed with the non-piecewise.

Split Conifer into Conifer and Open-conifer (LCC 20), sees if model improves.
```{R}
`fitted_5cl_+_20` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10),      # Conifer
      c(34:35),        # Disturbed
      c(16:19, 21:32), # Non-treed
      20,              # Open-conifer
      c(2:5, 11:15),   # Other treed
      19               # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20')$fireSense_FrequencyFitted$AIC`

Model converged and AIC improves significantly. Next check if we can separate

  - 6, 7 and 9 from the `Conifer` class.
  - 13 from the `Other treed` class.
  - 15, 17, 24, and 32 from the `Non-treed` class.

```{R}
`fitted_5cl_+_20_6` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 7:10),      # Conifer
      6,               # Conifer (Medium density, moss)
      c(34:35),        # Disturbed
      c(16:19, 21:32), # Non-treed
      20,              # Open Conifer
      c(2:5, 11:15),   # Other treed
      19               # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_6')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_6')$fireSense_FrequencyFitted$AIC`

Model converged but did not improve.

```{R}
`fitted_5cl_+_20_7` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6, 8:10),    # Conifer
      7,                # Conifer (Medium-density, lichen + shrub)
      c(34:35),         # Disturbed
      c(16:19, 21:32),  # Non-treed
      20,               # Open Conifer
      c(2:5, 11:15),    # Other treed
      19                # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_7')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_7')$fireSense_FrequencyFitted$AIC`

Model converged and AIC improves significantly.

```{R}
`fitted_5cl_+_20_9` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10),      # Conifer
      c(34:35),        # Disturbed
      c(16:19, 21:32), # Non-treed
      20,              # Open-conifer
      c(2:5, 11:15),   # Other treed
      19               # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_9')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_9')$fireSense_FrequencyFitted$AIC`

Model converged but did not improve.

```{R}
`fitted_5cl_+_20_13` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10),           # Conifer
      c(34:35),             # Disturbed
      13,                   # Mixedwoods (Conifer-dominated)
      c(16:19, 21:32),      # Non-treed
      20,                   # Open Conifer
      c(2:5, 11:12, 14:15), # Other treed
      19                    # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_13')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_13')$fireSense_FrequencyFitted$AIC`

Model converged and AIC improves significantly.

```{R}
`fitted_5cl_+_20_15` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10),      # Conifer
      c(34:35),        # Disturbed
      15,              # Low regenerating young mixed cover
      c(16:19, 21:32), # Non-treed
      20,              # Open Conifer
      c(2:5, 11:14),   # Other treed
      19               # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_15')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_15')$fireSense_FrequencyFitted$AIC`

Model did not converge.

```{R}
`fitted_5cl_+_20_17` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10),          # Conifer
      c(34:35),            # Disturbed
      17,                  # Grassland
      c(16, 18:19, 21:32), # Non-treed
      20,                  # Open Conifer
      c(2:5, 11:15),       # Other treed
      19                   # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_17')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_17')$fireSense_FrequencyFitted$AIC`

Model converged but did not improve.

```{R}
`fitted_5cl_+_20_24` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10),             # Conifer
      c(34:35),               # Disturbed
      24,                     # Lichen-shrub
      c(16:19, 21:23, 25:32), # Non-treed
      20,                     # Open Conifer
      c(2:5, 11:15),          # Other treed
      19                      # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_24')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_24')$fireSense_FrequencyFitted$AIC`

Model did not converge.

```{R}
`fitted_5cl_+_20_32` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6:10),      # Conifer
      c(34:35),        # Disturbed
      32,              # Lichen-spruce bog
      c(16:19, 21:31), # Non-treed
      20,              # Open Conifer
      c(2:5, 11:15),   # Other treed
      19               # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_32')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_32')$fireSense_FrequencyFitted$AIC`

Model did not converge.

We can separate 7 from the `Conifer` class and 13 from the `Other treed` class. Time to check if the model with 8 classes converges.

```{R}
`fitted_5cl_+_20_7_13` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6, 8:10),        # Conifer
      7,                    # Conifer (Medium density)
      13,                   # Mixedwoods (Conifer-dominated)
      c(34:35),             # Disturbed
      c(16:19, 21:32),      # Non-treed
      20,                   # Open Conifer
      c(2:5, 11:12, 14:15), # Other treed
      19                    # Wetlands
    ),
    pw = FALSE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_7_13')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_7_13')$fireSense_FrequencyFitted$AIC`

Model converged and AIC improves significantly.

Try fitting the same model with piecewise terms.

```{R}
`fitted_5cl_+_20_7_13_full_pw` <- Cache(
  fit,
  mk_formula(
    list(
      c(1, 6, 8:10),        # Conifer
      7,                    # Conifer (Medium density)
      13,                   # Mixedwoods (Conifer-dominated)
      c(34:35),             # Disturbed
      c(16:19, 21:32),      # Non-treed
      20,                   # Open Conifer
      c(2:5, 11:12, 14:15), # Other treed
      19                    # Wetlands
    ),
    pw = TRUE
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_7_13_full_pw')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_7_13_full_pw')$fireSense_FrequencyFitted$AIC`

Model did not converge but suggests that a breakpoint may exist for classes Disturbed and Wetlands.

Try adding a piecewise term just for Disturbed and Wetlands.

```{R}
`fitted_5cl_+_20_7_13_pw` <- Cache(
  fit,
  formula(
    n_fires ~ 
      I(cl1 + cl6 + cl8 + cl9 + cl10):MDC06 + 
      I(cl7):MDC06 + I(cl13):MDC06 + 
      I(cl34 + cl35):MDC06 + I(cl34 + cl35):pw(MDC06, k_cl34_cl35) +
      I(cl16 + cl17 + cl18 + cl19 + cl21 + cl22 + cl23 + cl24 + cl25 + cl26 + cl27 + cl28 + cl29 + cl30 + cl31 + cl32):MDC06 + 
      I(cl20):MDC06 +
      I(cl2 + cl3 + cl4 + cl5 + cl11 + cl12 + cl14 + cl15):MDC06 + 
      I(cl19):MDC06 + I(cl19):pw(MDC06, k_cl19) - 1
  ), 
  dataFireSense_FrequencyFit
)
```

Convergence: `r get('fitted_5cl_+_20_7_13_pw')$fireSense_FrequencyFitted$convergence`\
AIC: `r get('fitted_5cl_+_20_7_13_pw')$fireSense_FrequencyFitted$AIC`

Model converged and AIC improves significantly.
