---
title: "fireSense_NWT_DataPrep"
author: ""
date: "06 February 2019"
output: pdf_document
---

# Overview
The purpose of this module is to prepare the climate and vegetation data needed to run the fireSense modules for BCR6 and BCR6 contained in the Northwest Territories.

### Reclassify LCC2005 (39 classes)

|Description|Code|
| ------------------------------------------- |-----:|
|Temperate or subpolar needle-leaved evergreen closed tree canopy|1|
|Cold deciduous closed tree canopy|2|
|Mixed needle-leaved evergreen – cold deciduous closed tree canopy|3|
|Mixed needle-leaved evergreen – cold deciduous closed young tree canopy|4|
|Mixed cold deciduous - needle-leaved evergreen closed tree canopy|5|
|Temperate or subpolar needle-leaved evergreen medium density, moss-shrub understory|6|
|Temperate or subpolar needle-leaved evergreen medium density, lichen-shrub understory|7|
|Temperate or subpolar needle-leaved evergreen low density, shrub-moss understory|8|
|Temperate or subpolar needle-leaved evergreen low density, lichen (rock) understory|9|
|Temperate or subpolar needle-leaved evergreen low density, poorly drained|10|
|Cold deciduous broad-leaved, low to medium density|11|
|Cold deciduous broad-leaved, medium density, young regenerating|12|
|Mixed needle-leaved evergreen - cold deciduous, low to medium density|13|
|Mixed cold deciduous - needle-leaved evergreen, low to medium density|14|
|Low regenerating young mixed cover|15|
|High-low shrub dominated|16|
|Grassland|17|
|Herb-shrub-bare cover|18|
|Wetlands|19|
|Sparse needle-leaved evergreen, herb-shrub cover|20|
|Polar grassland, herb-shrub|21|
|Shrub-herb-lichen-bare|22|
|Herb-shrub poorly drained|23|
|Lichen-shrub-herb-bare soil|24|
|Low vegetation cover|25|
|Cropland-woodland|26|
|High biomass cropland|27|
|Medium biomass cropland|28|
|Low biomass cropland|29|
|Lichen barren|30|
|Lichen-sedge-moss-low shrub wetland|31|
|Lichen-spruce bog|32|
|Rock outcrops|33|
|Recent burns|34|
|Old burns|35|
|Urban and Built-up|36|
|Water bodies|37|
|Mixes of water and land|38|
|Snow/ice|39|
\  

Reclassified as:
\  

|Description|Code|
| ---- | -----:|
|Conifer|1|
|Crops|2|
|Deciduous|3|
|Disturbed|4|
|Mixed C-dom|5|
|Mixed Young|6|
|Mixed F-dom|7|
|Non-vascular|8|
|Open-conifer|9|
|Shrub|10|
|Wetlands|11|

\  

```{R Reclassify LCC05 39 classes}
rcl <- matrix(
  #   from,   to,   becomes
  c(     -1,  0.01,      14, # After visual inspection, likely herbs/shrubs
       0.99,  1.01,       1,
       1.99,  2.01,       5,
       2.99,  3.01,       7,
       3.99,  4.01,       8,
       4.99,  5.01,       9,
       5.99, 10.01,       1,
      10.99, 12.01,       5,
      12.99, 13.01,       7,
      13.99, 14.01,       9,
      14.99, 15.01,       6,
      15.99, 16.01,      14,
      16.99, 17.01,      10,
      17.99, 18.01,      14,
      18.99, 19.01,      15, # Wetlands, waiting for Tati's update
      19.99, 20.01,      11,
      20.99, 24.01,      14,
      24.99, 25.01,      10,
      25.99, 29.01,       4,
      29.99, 31.01,      10,
      31.99, 32.01,      15, # Wetlands (here lichen-spruce bog), waiting for Tati's update
      32.99, 33.01,       0, # do not burn
      33.99, 35.01,       6,
      35.99, 39.01,       0  # do not burn
  ),
  ncol = 3,
  byrow = TRUE
)


LCC05_BCR6_rcl <- Cache(reclassify, x = LCC05_BCR6, rcl = rcl)
LCC05_BCR6_NWT_rcl <- Cache(reclassify, x = LCC05_BCR6_NWT, rcl = rcl)
```

### LCC05 with incremental disturbances
```{R}
NFDB_PO_BCR6_NWT <- Cache(
  prepInputs,
  url = "https://drive.google.com/open?id=15Fl6XCsNTZtA2G3py0Ma5ZTaESWwn622",
  targetFile = "NFDB_poly_20180726_BCR6_NWT.shp",
  alsoExtract = "similar",
  fun = "sf::st_read"
)

prop_disturbed <- lapply(
  2000:2010,
  function(year)
  {
    Cache(
      rasterize,
      x = as(
        st_union(
          filter(NFDB_PO_BCR6_NWT, YEAR > (year - 15) & YEAR <= year)
        ),
        "Spatial"
      ),
      y = LCC05_BCR6_NWT, 
      getCover = TRUE
    )
  }
)

invisible(
  mapply(
    prop_disturbed,
    year = 2000:2010,
    function(x, year)
    {
      LCC05_BCR6_NWT_rcl[x[] >= .5] <- 6 # Code for disturbed areas
      writeRaster(LCC05_BCR6_NWT_rcl, filename = paste0("LCC05_BCR6_NWT_rcl_", year, ".tif"))
    },
    SIMPLIFY = FALSE,
    USE.NAMES = FALSE
  )
)
```


### Calculate the proportion covered by each class of land cover at 10km resolution, 2000-2010 period
```{R}
n_lcc <- 12

pp_lcc_10k <- 
  lapply(
    0:(n_lcc - 1),
    function(cl_i)
    {
      calc_prop_lcc <- function(x, cl = cl_i, na.rm = TRUE)
      {
        if (anyNA(x)) return(NA)
        sum(x == cl, na.rm = na.rm) / 1600
      }
      
      col_name <- paste0("cl", cl_i)
      
      tibble(
        !!col_name := aggregate(LCC05_BCR6_NWT_rcl, fact = 40, fun = calc_prop_lcc)[]
      )
    }
  ) %>% bind_cols %>% rowid_to_column(var = "PX_ID") %>% filter_at(2, all_vars(!is.na(.)))
```


# Fire data
### Prepare point data
```{R}
NFDB_PT_BCR6_NWT <- Cache(
  prepInputs,
  url = "https://drive.google.com/open?id=1HU2lGMYmMoyXkDVjYLGhvAiC0ZkY-XMg",
  targetFile = "NFDB_point_20181129_BCR6_NWT.shp",
  alsoExtract = "similar",
  fun = sf::st_read
)

NFDB_PT_BCR6_NWT <- NFDB_PT_BCR6_NWT %>%
  # Filter fire data (2000 - 2010 period)
  filter(YEAR >= 2000 & YEAR <= 2010) %>%
  
  # Drop columns containing info we don't need
  select(LATITUDE, LONGITUDE, YEAR, SIZE_HA, CAUSE) %>%

  # Keep only lightning fires
  filter(CAUSE == "L")
```




