---
title: "MDC DataPrep"
author: "Jean Marchal"
date: "February, 2019"
output: html_document
---

The purpose of this file is to document how we produced annual Monthly Drought Code (MDC) data for BCR6 and BCR6 contained in the Northwest Territories.

# Setup
```{r packages, message=FALSE}
library(dplyr)
library(ff)
library(lubridate)
library(raster)
library(reproducible)
library(sf)
library(sp)
library(tibble)
library(tidyselect)

options(reproducible.overwrite = TRUE)
knitr::opts_chunk$set(eval = FALSE)
```

# Prepare ClimateNA inputs - 250m and 1km resolution
```{R}
#
# Need to have 3 things: lat, long, elevation
#
#
## Load BCR6_RT, raster version of the BCR6 study area
#
BCR6_RT_250m <- prepInputs(
  url = "https://drive.google.com/open?id=1sEiXKnAOCi-f1BF7b4kTg-6zFlGr0YOH",
  targetFile = "bcr6.tif"
)

DEM_BCR6_250m <- prepInputs(
  url = "https://drive.google.com/open?id=1_7L8QDozDtGSuYWBKKkgzCABocR9lWVN"
)

#
## Produce 1km versions of BCR6 and DEM
#
BCR6_RT_1km <- Cache(
  aggregate,
  BCR6_RT_250m,
  fact = 4
)

DEM_BCR6_1km <- Cache(
  postProcess,
  DEM_BCR6_250m,
  method = "bilinear",
  rasterToMatch = BCR6_RT_1km,
  maskWithRTM = TRUE
)

prep_ClimateNA_inputs <- function(res)
{
  BCR6 <- get(paste0("BCR6_RT_", res))
  DEM <- get(paste0("DEM_BCR6_", res))
  
  withinBCR6 <- !is.na(BCR6[])
  elev <- DEM[withinBCR6]
  
  #
  ## Parts of the BCR6 where we have no data, after manual inspection, they are pixels
  ## in the sea. Confirmed by Diana. Remove these pixels from BCR6.
  #
  withinBCR6 <- which(withinBCR6)[!is.na(elev)]
  elev <- elev[!is.na(elev)]
  
  #
  # Write lat, long, elev to csv
  #
  np <- 8 # Split in 8 parts to stay within memory limits and because we have 8 threads available...
  wp <- rep(1:np, length.out = length(elev))
  
  for (i in 1:np)
  {
    f <- file(
      paste0("climateNA_inputs", i, "_", res, ".csv"), 
      "wb" # Use binary mode to prevent OS dependent behaviour for eol
    )
    
    write.csv(
      (
        bind_cols(
          (
            st_as_sf(
              as_tibble(
                raster::xyFromCell(BCR6, withinBCR6[wp == i])
              ),
              coords = c("x", "y"),
              crs = proj4string(DEM)
            ) %>%
              st_transform(crs = 4326) %>%
              st_coordinates() %>%
              as_tibble() %>%
              rename(lat = Y, long = X)
          ),
          tibble(el = elev[wp == i])
        ) %>%
          mutate(ID1 = withinBCR6[wp == i], ID2 = "") %>%
          dplyr::select(ID1, ID2, lat, long, el)
      ),
      file = f,
      row.names = FALSE,
      eol = "\r\n" # ClimateNA is windows software
    )
    
    close(f)
  }
}

prep_ClimateNA_inputs("250m")
prep_ClimateNA_inputs("1km")

```

# Read and filter ClimateNA outputs
Climate variables are described in the [AdaptWest paper](https://dx.doi.org/10.1371/journal.pone.0156720)
```{R}
# Add a check for NA (-9999 value)

read_ClimateNA_outputs <- function(files)
{
  climateNA_outputs <- do.call(
    "rbind",
    lapply(
      files,
      read.csv.ffdf,
      header = TRUE,
      colClasses = c("integer", "integer", "factor", rep("numeric", 171))
    )
  )
  
  climateNA_outputs[
    ,
    vars_select(
      colnames(climateNA_outputs), 
      Year, ID1, Latitude, Longitude, 
      num_range("Tmax", 4:9, 2), num_range("PPT",  4:9, 2)
    )
  ]
}

climateNA_outputs_250m <- read_ClimateNA_outputs(dir(pattern = "climateNA_outputs_.*_250m[.]csv$"))
climateNA_outputs_1km <- read_ClimateNA_outputs(dir(pattern = "climateNA_outputs_.*_1km[.]csv$"))
```

# Calculate MDC (April - September)
Calculate the Monthly Drought Code following [Bergeron et al. 2010](https://dx.doi.org/10.1071/WF09092):

$$Q = 800e^{-DC/400}$$
$$E_m = n(0.36(\bar{T}_{mx}) + L_f)$$
$$DC_{HALF} = MDC_0 + 0.25E_m$$
$$Q_{mr} = 3.937RM_{EFF}/800e^{-MDC_0/400}$$
$$DC_{mr} = DC_{HALF} - 400ln(1+Q_{mr})$$
$$MDC_m = DC_{mr} + 0.25E_m$$
$$MDC = (MDC_0 + MDC_m) / 2$$

Abbreviations:

  * $DC_{HALF}$: drying taking place over the first half of the month
  * $DC_{mr}$: drying taking place over the middle of the month
  * $MDC_0$: MDC from the end of the previous month
  * $MDC_m$: MDC at the end of the month
  * $E_m$: evapotranspiration over month
  * $L_f$: standard day-length adjustement factor
  * $n$: number of days in the month
  * $Q$: moisture equivalent
  * $Q_{mr}$: moisture equivalent in the layer after rain
  * $r_m$: total monthly rainfall
  * $RM_{EFF}$: effective rainfall
  * $T_{mx}$: monthly mean of daily max temperatures

```{R}
calc_MDC <- function(climateNA_outputs)
{
  # Day length adjustement L_f in Drought Code (taken from Van Wagner 1987)
  L_f <- function(month)
  {
    c(
      '4' = 0.9, 
      '5' = 3.8,
      '6' = 5.8, 
      '7' = 6.4, 
      '8' = 5.0,
      '9' = 2.4
    )[[as.character(month)]]
  }
  
  MDC_0 <- 0

  for (i in 4:9)
  {
    n <- unname(days_in_month(date(paste0(climateNA_outputs[["Year"]], "-0", i, "-01"))))
    T_mx <- climateNA_outputs[[paste0("Tmax0", i)]] # Max monthly temperature
    r_m <- climateNA_outputs[[paste0("PPT0", i)]]   # Total monthly precip
    E_m <- n * (.36 * T_mx + L_f(i))
    RM_EFF <- .83 * r_m
    Q_mr <- 3.937 * RM_EFF / (800 * exp(-MDC_0/400))
    DC_HALF <- MDC_0 + .25 * E_m
    DC_mr <- DC_HALF - 400 * log(1 + Q_mr)
    MDC_m <- DC_mr + .25 * E_m
    climateNA_outputs[[paste0("MDC0", i)]] <- MDC_0 <- (MDC_0 + MDC_m) / 2
  }
  
  climateNA_outputs[
    ,
    vars_select(
      colnames(climateNA_outputs), 
      Year, ID1, num_range("MDC", 4:9, 2)
    )
  ]
}

MDC_250m <- calc_MDC(climateNA_outputs_250m)
MDC_1km <- calc_MDC(climateNA_outputs_1km)
```

### Produce and save MDC rasters for the 2000-2010 period and the BCR6, 250m and 1km resolutions
``` {R}
save_MDC_RT <- function(res)
{
  BCR6 <- get(paste0("BCR6_RT_", res))
  MDC <- get(paste0("MDC_", res))
  
  for (year in 2000:2010)
  {
    lapply(
      4:9,
      function(month)
      {
        BCR6[MDC[MDC[["Year"]] == year, "ID1"]] <-
               MDC[MDC[["Year"]] == year, paste0("MDC", month)]
        print(
          writeRaster(
            BCR6, 
            filename = paste0("MDC0", month, "_", year, "_BCR6_", res, ".tif")
          )
        )
      }
    )
  }
}

save_MDC_RT("250m")
save_MDC_RT("1km")
```
